export const AttachmentAllowedMimeTypesConstant = {
  CSS: 'text/css',
  CSV: 'text/csv',
  DOC: 'application/msword',
  DOCX: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
  GIF: 'image/gif',
  HTML: 'text/html',
  JAVA_SCRIPT: 'text/javascript',
  JPEG: 'image/jpeg',
  JSON: 'application/json',
  MP4: 'video/mp4',
  MPEG: 'audio/mpeg',
  MS_VIDEO: 'video/x-msvideo',
  OGG: 'audio/ogg',
  PDF: 'application/pdf',
  PLAIN: 'text/plain',
  PNG: 'image/png',
  PPT: 'application/vnd.ms-powerpoint',
  PPTX: 'application/vnd.openxmlformats-officedocument.presentationml.presentation',
  TAR: 'application/x-tar',
  WAV: 'audio/wav',
  WEBM: 'video/webm',
  WEBP: 'image/webp',
  XLS: 'application/vnd.ms-excel',
  XLSX: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
  XML: 'application/xml',
  ZIP: 'application/zip',
};
