version: '3.8'

services:
  postgres_test:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'supersecret'
      POSTGRES_DB: 'postgres_test'
    ports:
      - 5432:5432
    volumes:
      - ./db:/docker-entrypoint-initdb.d/

  adminer_test:
    image: adminer
    restart: always
    ports:
      - 8081:8080
